force-app/main/default/objects/Environment__mdt/Environment__mdt.object-meta.xml
<CustomObject>
    <description>A parent record for other custom metadata records, so that they can be used in separate orgs</description>
    <label>Environment</label>
    <pluralLabel>Environments</pluralLabel>
</CustomObject>

force-app/main/default/objects/Property__mdt/Property__mdt.object-meta.xml
<CustomObject>
    <description>A one-off value that does not require its own custom metadata type</description>
    <label>Property</label>
    <pluralLabel>Properties</pluralLabel>
</CustomObject>

force-app/main/default/objects/Property__mdt/fields/Environment__c.field-meta.xml
<CustomField>
    <fullName>Environment__c</fullName>
    <label>Environment</label>
    <referenceTo>Environment__mdt</referenceTo>
    <relationshipLabel>Properties</relationshipLabel>
    <relationshipName>Properties</relationshipName>
    <required>true</required>
    <type>MetadataRelationship</type>
</CustomField>

unPackaged/main/default/classes/EnvironmentPropertiesTest.cls
/**
 * @author aidan@nebulaconsulting.co.uk
 * @date 24/02/2021
 */

@IsTest
private class EnvironmentPropertiesTest {

    @IsTest
    static void testBehavior() {
        String value = EnvironmentProperties.get('My_Label');
        System.assertEquals([SELECT Value__c FROM Property__mdt WHERE Environment__r.DeveloperName = 'Specific'].Value__c, value);
    }

    @IsTest
    static void overrideEnvironment() {
        EnvironmentProperties.environmentProperties = new EnvironmentMetadata(Property__mdt.SObjectType, Property__mdt.Key__c)
                .overrideEnvironment('https://nomatch.com');
        String value = EnvironmentProperties.get('My_Label');
        System.assertEquals([SELECT Value__c FROM Property__mdt WHERE Environment__r.DeveloperName = 'Default'].Value__c, value);
    }
}